services:
  link-up-app:
    build:
      context: ./app
    environment:
      NODE_ENV: production
      VITE_PUBLIC_API_BASE_URL: http://localhost:3000
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app/src
          target: /app/src
          action: sync


  #volumes:
  #database:
